# Wallpaper

output * bg $HOME/Downloads/tree.jpg fill

# Example monitor configs

# output HDMI-A-1 resolution 1920x1080@100Hz
# output HDMI-A-1 position 0,0

# Cursor theme
# seat seat0 xcursor_theme Bibata-Modern-Ice 24
