# Environment

exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

# Keyring

exec /usr/bin/gnome-keyring-daemon --start --components=secrets

# XDG autostart

exec dex --autostart --environment sway

exec notify-update

# Clipboard history

exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store

# Night light

exec wlsunset -T 6500 -t 3000 -l 14.6 -L 121.0
