# Applications

bindsym $mod+Return exec $term
bindsym $mod+d exec $menu

# Kill window
bindsym $mod+x kill

# Reload
bindsym $mod+Shift+c reload

# Floating modifier
floating_modifier $mod normal

# Focus movement
bindsym $mod+$left focus left
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# Move windows
bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# File manager
bindsym $mod+Shift+Return exec yazi

# Browser
bindsym $mod+Shift+b exec firefox

# Clipboard history
bindsym $mod+c exec cliphist list | rofi -dmenu | cliphist decode | wl-copy

# Emoji picker
bindsym $mod+period exec rofi -show emoji

bindsym $mod+Backspace exec uwsm-app power-menu

bindsym $mod+Alt+L exec pkill hyprlock || hyprlock
