# Borders

# default_border pixel 0
#
# for_window [class="^.*"] border pixel 0
# for_window [app_id="^.*"] border pixel 0

# Colors

# client.focused   #414868 #414868 #414868 #414868 #414868
# client.unfocused #414868 #414868 #414868 #414868 #414868

# Gaps

# gaps inner 5
# gaps outer 0

# Bar

bar {
    swaybar_command waybar
}
