# Window rules
for_window [title="Picture-in-Picture"] floating enable

# Pavucontrol

for_window [app_id="pavucontrol"] floating enable

# Blueman

for_window [app_id="blueman-manager"] floating enable

# File picker dialogs

for_window [window_role="pop-up"] floating enable
for_window [window_role="dialog"] floating enable

# Authentication dialogs

for_window [title="Authentication Required"] floating enable

# Keep launchers floating

for_window [app_id="rofi"] floating enable
