[preferred]
# Use GTK for most things (files, notifications)
default=gtk
# Use GNOME specifically for ScreenSharing
org.freedesktop.impl.portal.ScreenCast=gnome
org.freedesktop.impl.portal.Screenshot=gnome
# Use GNOME for settings (needed for some apps to recognize dark mode/sharing)
org.freedesktop.impl.portal.Settings=gtk;gnome
