# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\W]-> '

bind '"\ej": history-search-forward'
bind '"\ek": history-search-backward'

export PATH="$HOME/Bansuri/scripts:$PATH"
export PATH="$HOME/AUR/cursor-cli/dist-package:$PATH"
. "$HOME/.cargo/env"
